<?php

use App\Product;
use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    
	private $arrayProductos = array(
		array (
			"id"=>1,
			"object"=>"Ordenador",
			"name"=>"Portatil",
			"brand"=>"HP",
			"model"=>"255 G6",
			"description"=>"Este equipo incorpora un procesador APU AMD E2 de modelo E2-9000e, con velocidad de rendimiento de hasta 2 GHz y una RAM de 4 GB de memoria DDR3L. Juntos te permitirán trabajar, escuchar música y navegar por internet sin bloqueos. Así que ya sabes, llévatelo al trabajo o donde quieras, ya que con esta potencia te responderá ante todo lo que necesites.",
			"specifications"=>"Resolución: 1366 x 768 píxeles\r\nCalidad de imagen: HD\r\nTipo de pantalla: 15.6\"LED HD\r\nMemoria RAM: 4 GB\r\nProcesador: AMD E2-9000 (2 x 1.8 GHz)\r\nVelocidad Procesador: 1,5 GHz, hasta 2 GHz\r\nNúmero de Nucleos: 2",
			"price"=>280,
			"categoryid"=>1,
			"subcategoryid"=>1,
			"providerid"=>1,
			"imgRoute"=>"Productos\/Informatica\/Portatil\/hp01.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>2,
			"object"=>"Ordenador",
			"name"=>"Portatil",
			"brand"=>"HP",
			"model"=>"Notebook 15-da0018ns",
			"description"=>"Este equipo incorpora un procesador Intel Core i3-7020U, con velocidad de rendimiento de hasta 2.3 GHz y una RAM de 4 GB de memoria DDR4. Juntos te permitirán trabajar, escuchar música y navegar por internet sin bloqueos, así que ya sabes, llévatelo al trabajo o donde quieras, ya que con esta potencia te responderá ante todo lo que necesites. ¡Y con mucho color! Alucina con las imágenes en alta definición de la pantalla del HP de 15.6 pulgadas y resolución HD de 1366 x 768 píxeles con retroiluminación WLED, con la que podrás visualizar perfectamente la pantalla desde cualquier ángulo.",
			"specifications"=>"Resolución: 1366 x 768 píxeles \r\nCalidad de imagen: HD \r\nTipo de pantalla: 15.6\"WLED HD \r\nTipo de RAM: DDR4 \r\nMemoria RAM: 4 GB \r\nProcesador: Intel Core i3-7020U (2 x 2.3 GHz) \r\nTamaño de caché: 3 MB",
			"price"=>430,
			"categoryid"=>1,
			"subcategoryid"=>1,
			"providerid"=>1,
			"imgRoute"=>"Productos\/Informatica\/Portatil\/hp02.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>3,
			"object"=>"Ordenador",
			"name"=>"Portatil",
			"brand"=>"HP",
			"model"=>"Notebook 15-da0031ns",
			"description"=>"La eficiencia de todas tus instrucciones cuando las ejecutas en el ordenador portátil HP 15-DA0031NS lo soporta la tecnología Intel con su modelo Intel Core i3 y frecuencia de 2.3 GHz, velocidad que necesitas para trabajar con todo tipo de programas sin ningún problema. Además, para complementar la fuerza del procesador dispone de 8 GB de memoria RAM, cantidad que te servirá para ejecutar múltiples procesos.",
			"specifications"=>"Tamaño pantalla (cm\/pulg): - \/ 15.6 \r\nResolución: 1366 x 768 píxeles\r\nCalidad de imagen: HD\r\nTamaño pantalla (pulgadas): 15.6 \r\nTipo de pantalla: 15.6\"WLED HD\r\nTipo de RAM: DDR4\r\nMemoria RAM: 8 GB",
			"price"=>500,
			"categoryid"=>1,
			"subcategoryid"=>1,
			"providerid"=>1,
			"imgRoute"=>"Productos\/Informatica\/Portatil\/hp03.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>4,
			"object"=>"Ordenador",
			"name"=>"Portatil",
			"brand"=>"HP",
			"model"=>"Pavilion 15-bc404ns",
			"description"=>"La velocidad lo es casi todo en el mundo de la informática. Este portátil de HP te va a ofrecer una rapidez espectacular gracias a su procesador Intel Core i7-8550U. El chip viene acompañado de 8 GB de memoria RAM para que lleves a cabo tantas tareas simultáneas como quieras, sin que ello haga mella en el rendimiento del equipo.",
			"specifications"=>"Tamaño pantalla (cm\/pulg): - \/ 15.6  \r\nTamaño pantalla (pulgadas): 15.6\r\nMemoria RAM: 8 GB \r\nProcesador: Intel Core i7-8550U \r\nTarjeta gráfica: GTX 1050 \r\nCapacidad disco duro: 1 TB \r\nWi-Fi: Sí",
			"price"=>700,
			"categoryid"=>1,
			"subcategoryid"=>1,
			"providerid"=>1,
			"imgRoute"=>"Productos\/Informatica\/Portatil\/hp04.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>5,
			"object"=>"Ordenador",
			"name"=>"Portatil",
			"brand"=>"Lenovo",
			"model"=>"Ideapad 330S-15IKBR",
			"description"=>"Tus películas, series, fotografías o simplemente tu navegación a Internet ahora tienen una nitidez nunca imaginada gracias a la tecnología de alta definición de la pantalla de este portátil. Su resolución HD de 1366x768 proporciona una imagen detallada, clarísima y con los colores más vivos que nunca.",
			"specifications"=>"Tamaño pantalla (cm\/pulg): - \/ 15.6\r\nBrillo: 220 cd\/m² \r\nCalidad de imagen: HD \r\nTamaño pantalla (pulgadas): 15.6 Formato de la pantalla: 16:9 \r\nMemoria RAM: 8 GB \r\nIntel Optane: 16 GB\r\n",
			"price"=>700,
			"categoryid"=>1,
			"subcategoryid"=>1,
			"providerid"=>1,
			"imgRoute"=>"Productos\/Informatica\/Portatil\/lenovo01.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>6,
			"object"=>"Ordenador",
			"name"=>"Portatil",
			"brand"=>"Apple",
			"model"=>"MacBook Pro Retina",
			"description"=>"El PC integra un Intel Core i5-5350U a 1.8 GHz de velocidad, capaz de conseguir los 2.9 GHz con Turbo Boost. Además de 8 GB de RAM para potenciar más si cabe el excelente rendimiento de tu Apple Macbook Air.\r\nGracias a la tarjeta gráfica Intel HD Graphics 6000 y la excelente resolución de pantalla de 1.440 x 900 píxeles, disfrutarás como nunca de tus juegos y pelis en el portátil Apple MacBook Air MQD32Y-A.",
			"specifications"=>"Resolución: 1440 x 900 píxeles \r\nCalidad de imagen: WXGA+ \r\nTipo de pantalla: 13.3 pulgadas LED HD \r\nMemoria RAM: 8 GB \r\nProcesador: Intel Core i5-5350U (2 x 1.8 GHz) \r\nVelocidad Procesador: 1.8 GHz - 2.9 GHz con Turbo Boost \r\nVel. turbo procesador: 2.9 GHz",
			"price"=>970,
			"categoryid"=>1,
			"subcategoryid"=>1,
			"providerid"=>1,
			"imgRoute"=>"Productos\/Informatica\/Portatil\/apple01.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>7,
			"object"=>"Ordenador",
			"name"=>"Portatil",
			"brand"=>"Apple",
			"model"=>"MacBook Air MQD32Y\/A",
			"description"=>"Apple incluye en este MacBook el Touch ID, con el que podrás desbloquear o comprar con Apple Pay con sólo tocar un botón. Gracias al registro de tu huella dactilar serás el único en poder acceder a tu equipo y realizar gestiones de pago. Además, innova colocando en el teclado la barra Touch Bar la cual muestra las acciones configuradas elegidas previamente para acceder de forma rápida. \r\nLa octava generación de Intel consigue funcionar a gran potencia, pero con mayor eficiencia energética que en las anteriores generaciones. Con su procesador i7-8750H y 16 GB de RAM ahora dispondrás de una frecuencia base de 2.2 GHz y una velocidad Turbo de hasta 4.1 GHz ahorrando en energía y maximizando el rendimiento; de esta manera obtendrás una autonomía de hasta 10 horas en reproducción.",
			"specifications"=>"Resolución: 2880 x 1800 píxeles \r\nTipo de pantalla: 15.4 pulgadas IPS Retina \r\nMemoria RAM: 16 GB \r\nProcesador: Intel Core i7-8750H (6 x 2.6 GHz) \r\nMarca del Procesador: Coffee Lake Modelo \r\nProcesador: I7-8750H \r\nVelocidad Procesador: 2.6 - 4.3 GHz",
			"price"=>2960,
			"categoryid"=>1,
			"subcategoryid"=>1,
			"providerid"=>1,
			"imgRoute"=>"Productos\/Informatica\/Portatil\/apple02.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>8,
			"object"=>"Ordenador",
			"name"=>"Portatil",
			"brand"=>"Acer",
			"model"=>"Aspire 1 A114-31-C9HF",
			"description"=>"Dispones de un procesador Intel Celeron Processor N3350 con una velocidad que alcanza los 2.08GHz en modo turbo y un total de 4GB de memoria RAM para que no tengas ningún problema mientras disfrutas de tu equipo. Además, gracias a su batería con una duración de hasta 9 horas, podrás llevarlo contigo a todas partes sin preocuparte de ir cargando con molestos cables.En alta definiciónVerás todo el contenido que quieras con imágenes a todo color gracias a su definición HD con 1366 x 768 píxeles y una tecnología de pantalla Acer CineCrystal LCD que te hará vivir una experiencia aún más completa. Lo complementa a la perfección sus altavoces estéreo integrados para que no te pierdas ni un solo detalle de lo que sucede en tu pantalla de 14 pulgadas.",
			"specifications"=>"Resolución: 1366 x 768 \r\nTipo de pantalla: 14 pulgadas LCD HD \r\nTipo de RAM: DDR3 \r\nMemoria RAM: 4 GB \r\nProcesador: Intel Celeron N3350 \r\nVel. turbo procesador: 2.08 GHz \r\nTamaño de caché: 2 MB",
			"price"=>280,
			"categoryid"=>1,
			"subcategoryid"=>1,
			"providerid"=>1,
			"imgRoute"=>"Productos\/Informatica\/Portatil\/acer01.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>9,
			"object"=>"Ordenador",
			"name"=>"Portatil",
			"brand"=>"Acer",
			"model"=>"Aspire 3 A315-21-46PS",
			"description"=>"Este equipo cuenta con un procesador AMD A4-9125 gracias al cual podrás trabajar y cumplir con tus tareas diarias con solvencia y el rendimiento necesario. Le acompaña una memoria RAM de 8GB con la que podrás tener varias pestañas abiertas a la vez. Podrás disfrutar de la velocidad de arranque, el bajo ruido y el menor consumo gracias a su memoria SSD de 128GB que te permitirá disfrutar como nunca antes de tu equipo. Además, para que puedas transferir archivos de una forma ágil y rápida, dispones de puertos USB y un lector de tarjetas SD.",
			"specifications"=>"Resolución: 1366 x 768 píxeles\r\nCalidad de imagen: HD\r\nTipo de pantalla: 15.6 pulgadas LCD HD\r\nMemoria RAM: 8 GB\r\nProcesador: AMD A4-9125\r\nModelo Procesador: AMD A4-9125\r\nTipo Caché: 1MB",
			"price"=>350,
			"categoryid"=>1,
			"subcategoryid"=>1,
			"providerid"=>1,
			"imgRoute"=>"Productos\/Informatica\/Portatil\/acer02.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>10,
			"object"=>"Ordenador",
			"name"=>"Portatil",
			"brand"=>"Acer",
			"model"=>"Aspire 5 A515-51G-553U",
			"description"=>"Podrás ver los colores más vivos que nunca y disfrutar de una nitidez asombrosa con su tarjeta gráfica NVIDIA GeForce MX130. Dispones de una pantalla HD de 15.6 y tecnología Acer CineCrystal LED con la que podrás ver tus series y películas preferidas como nunca antes. Además, cuenta con altavoces estéreo integrados para que tu experiencia sea aún más completa. Y por si fuera poco, podrás compartirlo con quien quieras a través de su webcam HD y sin preocuparte de ir cargando con molestos cables, ya que su autonomía es de hasta 7 horas.",
			"specifications"=>"Resolución: 1366 x 768 \r\nTipo de pantalla: 15.6 pulgadas LED HD \r\nTipo de RAM: DDR4 \r\nMemoria RAM: 8 GB \r\nProcesador: Intel Core i5-8250U (4 x 1.66 GHz) \r\nModelo Procesador: Intel Core i5-8250U \r\nVelocidad Procesador: Desde 1.6GHz hasta los 2.08GHz en modo turbo",
			"price"=>700,
			"categoryid"=>1,
			"subcategoryid"=>1,
			"providerid"=>1,
			"imgRoute"=>"Productos\/Informatica\/Portatil\/acer03.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>11,
			"object"=>"Ordenador",
			"name"=>"Sobremesa",
			"brand"=>"HP",
			"model"=>"Slimline 290-p0001ns",
			"description"=>"Si necesitas trabajar con varias pestañas y documentos abiertos a la vez, no te preocupes. Su procesador Intel Core i3-8100 y los 8 GB de memoria RAM de los que dispone, serán tus mejores compañeros durante los ratos que tengas que pasar frente a ti equipo. Además, podrás disfrutar de una gran variedad de recursos con su fiable sistema operativo Windows 10 Home.",
			"specifications"=>"Procesador: Intel Core i3-8100 (4 x 3.6 GHz)\r\nTipo de RAM: DDR4\r\nMemoria RAM: 8 GB\r\nTarjeta gráfica: Intel HD Graphics 630\r\nCapacidad disco duro: 1 TB\r\nConexiones: 8 USB \/ HDMI \/ VGA\r\nWi-Fi: 802.11a\/b\/g\/n\/ac\r\nSistema operativo: Windows 10",
			"price"=>500,
			"categoryid"=>1,
			"subcategoryid"=>2,
			"providerid"=>2,
			"imgRoute"=>"Productos\/Informatica\/Sobremesa\/hp01.png",
			"stock"=>20,
			"taxesid"=>2
		),
		array (
			"id"=>12,
			"object"=>"Ordenador",
			"name"=>"Sobremesa",
			"brand"=>"HP",
			"model"=>"Pavilion Desktops 590-p0102ns",
			"description"=>"Disfruta de un PC de altos vuelos con el PC sobremesa HP PPavilion Desktops 590-p0102ns. Con un procesador AMD Ryzen 5 2400G y 8 GB de RAM podrás trabajar con un gran rendimiento. Además, podrás guardar todas tus partidas y archivos en un disco duro HDD de 1 TB.Procesador AMDLa gran versatilidad del HP Pavilion Pavilion Desktops 590-p0102ns se debe a su potente procesador AMD Quad-Core Ryzen 5 2400G con una frecuencia base de 3.6 GHz capaz de llegar hasta los 3.8 GHz. Esto, combinado con la memoria RAM de 8 GB te proporcionará un buen rendimiento día tras día.Tu almacén de datosLos problemas de espacio en el disco duro se van a acabar de un plumazo. La unidad interna HDD del HP Pavilion Desktops 590-p0102ns es de 1 TB que te permitirán guardar tantos archivos como quieras. Y lo mejor de todo es su velocidad de 7200 rpm que te asegurará un arranque rápido de Windows y una navegación entre carpetas fluida y sin esperas. Conexiones de todo tipoDisfruta de unos puertos súper completos para que conectes tantos periféricos y dispositivos como quieras. De entre todos ellos destaca el USB 3.0 Type C, de alta velocidad de transmisión para acortar esperas.",
			"specifications"=>"Procesador: AMD Ryzen 5 2400 G (4 x 3.6 GHz) \r\nVel. turbo procesador: 3.8 GHz \r\nTipo de RAM: DDR4 Memoria RAM: 8 GB \r\nTarjeta gráfica: AMD Radeon Vega 11 \r\nCapacidad disco duro: 1 TB \r\nChipset: AMD Promontory FCH",
			"price"=>550,
			"categoryid"=>1,
			"subcategoryid"=>2,
			"providerid"=>2,
			"imgRoute"=>"Productos\/Informatica\/Sobremesa\/hp02.png",
			"stock"=>20,
			"taxesid"=>2
		),
		array (
			"id"=>13,
			"object"=>"Ordenador",
			"name"=>"Sobremesa",
			"brand"=>"HP",
			"model"=>"Slimline Desktop 290-p0000nsm",
			"description"=>"No te dejes engañar por el pequeño tamaño del HP Slimline Desktop 290-p0000nsm, ya que en su interior posee una gran potencia, inclusive mayor que algunos sobremesas más grandes. La clave de su potencia y rendimiento radica en su procesador de doble núcleo Intel Core i3-8100 con un caché de 6 MB y una velocidad de 3.6 GHz.\r\nA esto se le sume una memoria RAM bastante amplia, para ser precisos, viene con 4 GB de RAM del tipo DDR4 2400MHz.",
			"specifications"=>"Procesador: Intel Core i3 \r\nNúmero Procesador: 1 \r\nModelo Procesador: Intel Core i3-7100T \r\nNúmero de Nucleos: 4 \r\nTamaño de caché: 6 MB \r\nTipo de RAM: DDR4 \r\nMemoria RAM: 4 GB",
			"price"=>500,
			"categoryid"=>1,
			"subcategoryid"=>2,
			"providerid"=>2,
			"imgRoute"=>"Productos\/Informatica\/Sobremesa\/hp03.png",
			"stock"=>20,
			"taxesid"=>2
		),
		array (
			"id"=>14,
			"object"=>"Ordenador",
			"name"=>"Sobremesa",
			"brand"=>"Lenovo",
			"model"=>"Ideacentre 310S-08IGM",
			"description"=>"Si necesitas un equipo para tus tareas cotidianas tales como trabajar, estudiar, o consultar tu correo electrónico y páginas webs preferidas, con este PC sobremesa Lenovo Ideacentre 310S-08IGM tendrás todo lo que buscas. Práctico y ágil para tu día a día.\r\nSi necesitas trabajar con varias pestañas y documentos abiertos a la vez, no te preocupes. Su procesador Intel Celeron® J4005 y los 4 GB de memoria RAM de los que dispone, serán tus mejores compañeros durante los ratos que tengas que pasar frente a ti equipo. Además, podrás disfrutar de una gran variedad de recursos con su fiable sistema operativo Windows 10.",
			"specifications"=>"Procesador: Intel Celeron J4005 \r\nVelocidad Procesador: Hasta 2.7 GHz \r\nMarca del Procesador: Intel \r\nModelo Procesador: Celeron J4005 \r\nTipo de RAM: DDR4 \r\nTarjeta gráfica: Intel UHD Graphics 600\r\nCapacidad disco duro: 1 TB",
			"price"=>300,
			"categoryid"=>1,
			"subcategoryid"=>2,
			"providerid"=>2,
			"imgRoute"=>"Productos\/Informatica\/Sobremesa\/lenovo01.png",
			"stock"=>20,
			"taxesid"=>2
		),
		array (
			"id"=>15,
			"object"=>"Ordenador",
			"name"=>"Sobremesa",
			"brand"=>"Lenovo",
			"model"=>"Ideacentre 510-15ICB",
			"description"=>"El PC sobremesa Lenovo Ideacentre 510-15ICB con un procesador de 8 generación, 16 GB de RAM y un disco duro HDD de 1 TB y una SSD de 128GBpara que puedas almacenar una gran cantidad de archivos, fotos, música y lo que quieras.\r\nEl rendimiento del PC sobremesa Lenovo Ideacentre 510-15ICB irá, en su mayor parte, a cargo de la empresa californiana Intel. El procesador Intel Core i7-8700 te garantizará velocidades de hasta 4.6 GHz con las que podrás hacer cualquier cosa a gran velocidad y sin interrupciones.\r\nOtra de las grandes características del este ordenador es su disco duro de 1 TB HDD. Con 1000 GB tendrás la capacidad de almacenar toda clase de archivos sin miedo a quedarte corto. Y, además, su velocidad de 7200 rpm te permitirá iniciar Windows 10 Home y navegar entre carpetas a gran velocidad.",
			"specifications"=>"Procesador: Intel Core i7-8700 (6 x 3.2 GHz) \r\nVel. turbo procesador: 4.6 GHz \r\nNúmero de Nucleos: 6 \r\nTipo de RAM: DDR4 \r\nRAM: 8GBx2 DDR4-2666 \r\nTarjeta gráfica: Intel UHD Graphics 630 \r\nCapacidad SSD: 128 GB",
			"price"=>1000,
			"categoryid"=>1,
			"subcategoryid"=>2,
			"providerid"=>2,
			"imgRoute"=>"Productos\/Informatica\/Sobremesa\/lenovo02.png",
			"stock"=>20,
			"taxesid"=>2
		),
		array (
			"id"=>16,
			"object"=>"Ordenador",
			"name"=>"Sobremesa",
			"brand"=>"Predator",
			"model"=>"PC-GAMING G3-710",
			"description"=>"Si no quieres perderte nada en el campo de juego y luchar contra tus adversarios sin que se te escape ni un solo detalle, con este PC Gaming Predator G3-710 tendrás todo lo que necesitas. Gracias a su potencia ilimitada, el sonido real de campo de batalla y su diseño único te sentirás el número uno desde el primer día.\r\nNo habrá nada que se te resista gracias a su procesador de 7ª generación Intel Core i5-7400 y su potente memoria RAM de 16GB que se convertirán en tus mejores aliados cuando salgas a luchar.  ¿A qué esperas para empezar a ganarlo todo?\r\nCon su tarjeta gráfica Nvidia GTX 1050 de 2GB te parecerá que estás dentro de tus juegos y vivirás experiencias a todo color y con una calidad que te conquistará desde el minuto uno.",
			"specifications"=>"Procesador: Intel Core i5-7400 (4 x 3 GHz) \r\nVel. turbo procesador: 3.5 GHz \r\nNúmero Procesador: 1 \r\nModelo Procesador: Intel Core i5 7400 \r\nTamaño de caché: 6 MB \r\nMemoria RAM: 16 GB",
			"price"=>1200,
			"categoryid"=>1,
			"subcategoryid"=>2,
			"providerid"=>2,
			"imgRoute"=>"Productos\/Informatica\/Sobremesa\/predator01.png",
			"stock"=>20,
			"taxesid"=>2
		),
		array (
			"id"=>17,
			"object"=>"Tablet",
			"name"=>"",
			"brand"=>"Samsung",
			"model"=>"Galaxy Tab A T580",
			"description"=>"La sensacional pantalla de 10.1 pulgadas te permitirá visualizar películas, series o vídeos de Youtube de forma clara y extensa. Lo mismo ocurrirá con tus juegos y aplicaciones. Y lo mejor de todo es que la resolución Full HD te permitirá verlo todo sin perderte ningún detalle.\r\nTras esa maravillosa pantalla laten componentes de gama alta para asegurar un rendimiento top. El procesador Exynos de ocho núcleos es capaz de alcanzar unas frecuencias de 1.6 GHz, más que suficiente para mover fluídamente la mayoría de apps y juegos Android. Además, para complementar la velocidad, la tablet cuenta con 2 GB de memoria RAM que te asegurará un buen rendimiento multitarea.",
			"specifications"=>"Resolución: 1920 x 1200 píxeles\r\nCalidad de imagen: WUXGA\r\nTipo de pantalla: 10.1\"LED Full HD\r\nProcesador: Exynos 7870 (8 x 1.6 GHz)\r\nModelo Procesador: Exynos\r\nVelocidad Procesador: 1.6GHz\r\nNúmero de Nucleos: 8",
			"price"=>190,
			"categoryid"=>1,
			"subcategoryid"=>3,
			"providerid"=>3,
			"imgRoute"=>"Productos\/Informatica\/Tablets\/samsung01.png",
			"stock"=>20,
			"taxesid"=>3
		),
		array (
			"id"=>18,
			"object"=>"Monitor",
			"name"=>"",
			"brand"=>"MSI",
			"model"=>"Optix MAG27C",
			"description"=>"Disfruta de tus juegos como un auténtico gamer gracias al monitor gaming MSI Optix MAG27C de 27 pulgadas. Su resolución de alta calidad y su gran tiempo de respuesta te garantizan un rendimiento de altos vuelos para que lo visualices todo como si estuvieras dentro.\r\nPonte a jugar y disfruta de unas sesiones gaming de altos vuelos con una imagen de calidad gracias a su resolución Full HD (1920 x 1080). Y todo ello en una pantalla de 27 pulgadas con diseño curvo que te hará sumergirte en la misma pantalla. \r\nVive todas las aventuras de tus juegos como si estuvieras dentro. Sin cortes. Sin interrupciones. Su frecuencia de actualización de 144 Hz se une al sistema FreeSync para evitar desgarros de la pantalla y a un tiempo de respuesta de 1 ms para adelantarte a tus rivales y deshacerte de ellos con mayor facilidad.",
			"specifications"=>"Tamaño pantalla (cm\/pulg): 686 cm \/ 27 pulgadas\r\nCalidad de imagen: Full-HD\r\nResolución: 1920x1080\r\nFormato de la pantalla: 16:9\r\nTiempo de respuesta: 1",
			"price"=>300,
			"categoryid"=>1,
			"subcategoryid"=>4,
			"providerid"=>3,
			"imgRoute"=>"Productos\/Informatica\/Perifericos\/monitor01.png",
			"stock"=>20,
			"taxesid"=>3
		),
		array (
			"id"=>19,
			"object"=>"Camara",
			"name"=>null,
			"brand"=>"Nikon",
			"model"=>"D3400",
			"description"=>"Nikon nos trae la D3400 con un diseño pequeño y de uso fácil para que puedas llevártela a todas partes. Con sólo una carga completa de su batería podrás capturar hasta 1200 fotos -ya que es de bajo consumo- para que no se te escape ningún detalle. Además viene con Modo Guía el cual te indicará el ajuste que debes aplicar según el enfoque y el entorno.\r\nGracias al amplio rango de sensibilidades lumínicas ISO de 100 a 25 600, podrás capturas tu entorno con calidad y en alta resolución incluso en zonas de penumbra. Además, su sistema de enfoque automático te garantizará gran nitidez de lo enfocado y lo mantendrá así hasta que dispares",
			"specifications"=>"Resolución sensor: 24.2 megapixel\r\nSensibilidad ISO: ISO 100-25600, en pasos de 1 EV, Control automático de sensibilidad ISO disponible\r\nTipo de sensor: CMOS APS-C\r\nDistancia focal: 18-55 mm\r\nDistancia focal equivalente 35 mm: 27 - 82.5 mm\r\nTamaño pantalla (cm\/pulg): 7.6 cm \/ 3 \r\nTamaño pantalla (cm): 7.6 cm",
			"price"=>400,
			"categoryid"=>2,
			"subcategoryid"=>5,
			"providerid"=>3,
			"imgRoute"=>"Productos\/Fotografia\/Reflex\/nikon01.png",
			"stock"=>20,
			"taxesid"=>3
		),
		array (
			"id"=>20,
			"object"=>"Camara",
			"name"=>"",
			"brand"=>"Sony",
			"model"=>"ILCE 5100L",
			"description"=>"Esta cámara digital de Sony cuenta con el sistema Fast Hybrid AF con 179 puntos AF para un enfoque automático y enfoque y disparo del obturador tocando la pantalla táctil. Además, el Sensor APS-C de 24.3 MP y procesador Motor Bionz X te permitirán capturar una gran cantidad de detalles. Y todo esto con un manejo sencillo, tamaño reducido y con un peso sorprendentemente ligero. Te convertirás en todo un profesional.\r\nNo te limites solo a tomar fotos. Haz vídeos Full HD en XAVC S con enfoque profesional a 50 Mbps y saca al cineasta que llevas en ti. Podrás hacerlo todo de manera sencilla gracias a la pantalla LCD brillante que se inclina hasta 180º. Pero no solo eso, sino que la cámara EVIL Sony ILCE 5100L cuenta con funciones como Touch Focus y Touch Shutter que te permitirán enfocar y disparar con sólo dar un toque en la pantalla.\r\nColoca tu cámara EVIL Sony ILCE 5100L al lado de tu móvil o tablet iOS o Android con conexión Wi-Fi y comparte tus fotos al momento, ya que Smart Remote Control (preinstalado), hará que tengas el control de la cámara desde tu smartphone o tablet.",
			"specifications"=>"Resolución sensor: 24.3 megapixel\r\nProcesador de imagen: Bionz X\r\nSensibilidad ISO: Fotografías: equivalencia con ISO 100-16000 (en pasos de 1\/3 EV) \/ AUTO (ISO 100-16000, límite inferior y superior seleccionable) Películas: equivalencia con ISO 100-6400 (en pasos de 1\/3 EV), AUTO (ISO 100-6400, límite inferior y superior seleccionable)\r\nTipo de sensor: CMOS APS-C\r\nDistancia focal: 16-50 mm\r\nDistancia focal equivalente 35 mm: 24 - 75 mm\r\nTamaño pantalla (cm\/pulg): 7.6 cm \/ 3 \r\nTamaño pantalla (cm): 7.6 cm",
			"price"=>440,
			"categoryid"=>2,
			"subcategoryid"=>6,
			"providerid"=>2,
			"imgRoute"=>"Productos\/Fotografia\/Evil\/sony01.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>21,
			"object"=>"Objetivo",
			"name"=>"",
			"brand"=>"Canon",
			"model"=>"EF 50mm f\/1.8 STM",
			"description"=>"Objetivo de longitud focal fija, ideal para retratos y fotografías con poca iluminación. Cuenta con enfoque rápido y silencioso STM, perfecto para grabar vídeos.\r\nObtendrás imágenes con una gran nitidez tanto en fotografías como en vídeos gracias a su revestimiento Súper Spectra, que elimina las luces parásitas y el velo óptico. Con una menor distorsión, y un aumento de la nitidez y el contraste tus imágenes quedarán siempre compensadas y muy naturales. \r\nEs un objetivo perfecto para trabajar en situaciones de poca luz. Su f\/1.8 permite que entre mucha luz a la cámara, obteniendo resultados luminosos en cualquier situación. También responde muy bien en fotografía de retratos, ya que permite desenfocar el fondo para resaltar al sujeto sin tener que acercarte mucho a él. \r\nMultiplica las posibilidades de tu cámara réflex con el objetivo EF 50 mm f\/1.8 STM de Canon",
			"specifications"=>"Tipo: Focal Fija \r\nConexión para: Canon \r\nMontura objetivo: 6 elementos\/ 5 grupos \r\nDistancia focal máx: 50 mm \r\nApertura máxima: F\/1.8 \r\nClasificación lente: EF \r\nColor: Negro",
			"price"=>130,
			"categoryid"=>2,
			"subcategoryid"=>7,
			"providerid"=>2,
			"imgRoute"=>"Productos\/Fotografia\/Objetivos\/canon01.png",
			"stock"=>20,
			"taxesid"=>2
		),
		array (
			"id"=>22,
			"object"=>"Camara",
			"name"=>"",
			"brand"=>"GoPro",
			"model"=>"HERO7 Black",
			"description"=>"La cámara deportiva GoPro HERO7 Black te permite grabar vídeos en 4K60 y lograr fotos en 12MP, tan impresionantes como los propios momentos. Eso se traduce en una calidad profesional, con imágenes dignas de producción cinematográfica. Juega además con la función Súper Foto que optimiza el ruido de forma automática, o la opción Time Warp para hacer interesantes vídeos secuenciales. Con la opción cámara lenta, podrás grabar vídeos hasta 8x. Por si fuera poco, todo estará estabilizado con la tecnología HyperSmooth.\r\nLa videocámara outdoor GoPro HERO está equipada con Wi-Fi, GPS y Bluetooth para que siempre puedas estar conectado. Además, las fotos y videos pasan automáticamente a tus GoPro Apps para que puedas compartir el momento mientras lo vives o transformarlo en un vídeo perfectamente editado con música y efectos. ¿Fan de las redes sociales? Podrás retransmitir en directo los vídeos que hagas para que tus seguidores no pierdan ni un detalle.\r\nEnciende tu cámara de acción con tan solo apretar un botón y cambia rápidamente entre modos, consiguiendo la toma perfecta y revisando tu contenido en la pantalla táctil. Podrás tener control manos libres en tu GoPro mediante comandos de voz sencillos y fáciles de usar.",
			"specifications"=>"Tipo: Cámara de acción\r\nResolución de vídeo: 3840 x 2160 60 fps\r\nResolución fotos: 12 megapixel\r\nEstabilizador de imagen: Sí\r\nLente: Gran angular 170 grados\r\nFotogramas por Segundo: 60 fps",
			"price"=>416,
			"categoryid"=>2,
			"subcategoryid"=>8,
			"providerid"=>4,
			"imgRoute"=>"Productos\/Fotografia\/Deportivas\/gopro01.png",
			"stock"=>20,
			"taxesid"=>2
		),
		array (
			"id"=>23,
			"object"=>"Telefono",
			"name"=>"Movil",
			"brand"=>"Apple",
			"model"=>"iPhone Xs Max",
			"description"=>"El móvil Apple iPhone Xs Max de 64 GB de capacidad lleva integrado el sistema operativo iOS 12. Además incorpora el chip A12 Bionic con CPU de 6 núcleos, una GPU de 4 núcleos y Neural Engine de última generación integrado. El objetivo del Neural Engine es ampliar las posibilidades del aprendizaje automático del teléfono. Por eso puede reconocer patrones y basarse en experiencias previas para hacer predicciones. Es decir, aprende casi como tú. Es capaz de utilizar ese auto-aprendizaje en tiempo real para que disfrutes de las fotos, los juegos y la realidad aumentada de una forma totalmente nueva. Y todo esto llegando a ser hasta 9 veces más rápido que el anterior A11 Bionic. Rendimiento, inteligencia y eficiencia maximizados.\r\nSumérgete de lleno en la precisión de imagen con la gran pantalla Super Retina de 6.5\"y una resolución de 2688 x 1242 píxeles, siendo la más grande que ha tenido nunca un iPhone. Y al ser OLED y HDR, tendrás unos colores precisos, unos negros auténticos y un contraste espectacular. Su nitidez te dejará boquiabierto. Sonríe a la nueva era de la fotografía Apple siempre da un paso más. Es por eso que el móvil Apple iPhone Xs Max cuenta con una cámara trasera dual de 12 MP, con un objetivo gran angular de f\/1.8 y un teleobjetivo de f\/2.4. Su sensor avanzado es hasta 2 veces más rápido que en la versión anterior para que puedas utilizar el HDR inteligente en todas tus fotos. Además, incorpora el Modo Retrato que te garantizará un efecto bokeh mejorado y un nuevo Control de Profundidad de campo en los retratos. Y por si fuera poco, es capaz de grabar vídeo en calidad 4K de hasta 60 f\/s.",
			"specifications"=>"Sistema operativo: iOS \r\nProcesador: A12 Bionic (6 x 2.49 GHz) \r\nCapacidad memoria: 64 GB \r\nTipo de pantalla: Super Retina HD \r\nAlmacenamiento\/RAM: 64 GB \/ 4 GB \r\nCámara tras.\/frontal: Dual 12 + 12 Megapíxeles \/ 7 Megapíxeles \r\nSensores: Face ID",
			"price"=>1260,
			"categoryid"=>3,
			"subcategoryid"=>9,
			"providerid"=>5,
			"imgRoute"=>"Productos\/Telefonia\/Smartphones\/iphone01.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>24,
			"object"=>"Reloj",
			"name"=>"",
			"brand"=>"Samsung",
			"model"=>"Gear S3 Frontier",
			"description"=>"Lleva siempre contigo el smartwatch Samsung Gear S3 Frontier en color negro y mantente siempre en línea y en forma gracias a sus prestaciones. Viene con numerosas prestaciones y ventajas tanto si vas a una fiesta como de excursión.\r\nResponde tus llamadas, lee tus mensajes o accede a las aplicaciones que quieras con sólo girar el bisel del reloj; integra un altavoz con el que podrás gestionar tus llamadas. Además, gracias a la conectividad WiFi y Bluetooth podrás sincronizarlo con tus auriculares inalámbricos y responder desde estos (no incluidos).\r\nSu diseño tiene el aspecto de un reloj de alta gama por lo que podrás llevarlo contigo en todos tus eventos. Además, su revestimiento es resistente al agua y al polvo para que puedas llevarlo tanto a una fiesta como en la montaña, el smartwatch Samsung Gear S3 Frontier está preparado.",
			"specifications"=>"Procesador: Dual-Core\r\nCapacidad memoria: 4 GB\r\nVersión Bluetooth: 4.2\r\nWi-Fi: 802.11b\/g\/n\r\nNFC: Sí",
			"price"=>260,
			"categoryid"=>3,
			"subcategoryid"=>10,
			"providerid"=>7,
			"imgRoute"=>"Productos\/Telefonia\/Smartwatches\/samsung01.png",
			"stock"=>20,
			"taxesid"=>3
		),
		array (
			"id"=>25,
			"object"=>"Telefono",
			"name"=>"",
			"brand"=>"Motorola",
			"model"=>"C1002 DUO",
			"description"=>"Del Motorola C1002 DUO te van a sorprender varias cosas. Para empezar, no podrás resistirte a un precio de escándalo. Y, por otro lado, te encantarán sus prácticas funcionalidades. ¿No te lo crees? ¡Sigue leyendo!\r\nCon una memoria de hasta 50 contactos podrás almacenar los números más importantes para ti. De esta forma, no volverás a perder ningún contacto. \r\nAdemás, en su pantalla LCD retroiluminada podrás visualizar las llamadas entrantes, gracias a la identificación de llamadas. \r\nComo puedes ver, Motorola C1002 DUO, te ofrece todo lo que necesitas para disfrutar de un terminal sencillo y práctico.",
			"specifications"=>"Función manos libres: Sí\r\nManos libres: Sí\r\nNº de contactos: 50\r\nTipo: AAA",
			"price"=>30,
			"categoryid"=>3,
			"subcategoryid"=>11,
			"providerid"=>8,
			"imgRoute"=>"Productos\/Telefonia\/Telefoniadomestica\/motorola01.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>26,
			"object"=>"Juego",
			"name"=>"Resident Evil 2",
			"brand"=>"Sony",
			"model"=>"PS4",
			"description"=>"La pieza maestra que definió el género Resident Evil 2 regresa remodelado completamente desde cero para ofrecer una experiencia narrativa más profunda. Utilizando el motor gráfico RE Engine propiedad de Capcom, Resident Evil 2 ofrece una nueva perspectiva sobra la clásica saga survival horror, un apartado visual terroríficamente realista, un palpitante audio inmersivo, una nueva vista de cámara por encima del hombro y controles modernizados además de los modos de juego de la entrega original. En Resident Evil 2 regresa la acción clásica, la exploración llena de tensión y el estilo de resolución de puzles que definieron la saga Resident Evil. Los usuarios se unen al oficial de policía novato Leon S. Kennedy y a la estudiante universitaria Claire Redfield, que se ven empujados hacia un nefasto estallido en Raccoon City que transformó a su población en zombis mortales. Deben trabajar conjuntamente para sobrevivir y llegar al fondo de lo que hay detrás del terrible ataque. Tanto Leon como Claire cuentan con sus propias campañas jugables por separado, permitiendo que los jugadores vean la historia desde la perspectiva de ambos personajes.",
			"specifications"=>"Tipo: Juego PS4\r\nTitulo: Resident Evil 2\r\nClasificación por edades (PEGI): 18+\r\nEAN: 5055060946169",
			"price"=>55,
			"categoryid"=>4,
			"subcategoryid"=>12,
			"providerid"=>4,
			"imgRoute"=>"Productos\/Ocio\/Videojuegos\/residentevil.png",
			"stock"=>20,
			"taxesid"=>2
		),
		array (
			"id"=>27,
			"object"=>"Consola",
			"name"=>"",
			"brand"=>"Sony",
			"model"=>"PS4 1TB + 2 Mandos Dual Shock",
			"description"=>"La PlayStation 4 desarrollada por Sony es un dispositivo inteligente y versátil a través del cual descubrirás un mundo de entretenimiento que romperá con todas tus expectativas. Disfruta de películas en Blu-Ray, series de TV, música y un contenido en constante actualización con las novedades de PlayStation Network.\r\nJugar ya no será una experiencia de ficción. Siéntete parte del juego gracias a la impresionante nitidez de los gráficos de alta definición incorporados por la PlayStation 4. Sus potentes procesadores ultrarápidos y una memoria unificada de alto rendimiento fueron diseñados para que disfrutes de una amplia gama de juegos con absoluta fluidez.",
			"specifications"=>"Tipo: Consola \r\nModelo de consola: PS4 \r\nSlim Procesador: x86-64 AMD Jaguar, 8 Cores \r\nChip gráfico: 1.84 TFLOPS, AMD Radeon Based Graphics Engine \r\nMandos incluidos: 2 DualShock 4 \r\nUnidad de almacenamiento: Blu-ray + CD + DVD \r\nWi-Fi: Sí",
			"price"=>345,
			"categoryid"=>4,
			"subcategoryid"=>13,
			"providerid"=>1,
			"imgRoute"=>"Productos\/Ocio\/Consolas\/ps401.png",
			"stock"=>20,
			"taxesid"=>3
		),
		array (
			"id"=>28,
			"object"=>"TV",
			"name"=>"",
			"brand"=>"Samsung",
			"model"=>"UE55NU7175",
			"description"=>"El color cobra vida con el TV LED 55 pulgadas Samsung UE55NU7175. Disfruta de tu contenido y películas favoritas con colores vivos y brillantes, para no perder ni un solo detalle.\r\nEl TV LED 55 pulgadas Samsung UE55NU7175UXXC tiene una resolución 4K UHD real, lo que quiere decir que su definición es 4 veces superior a Full HD. Complementado con la tecnología PurColor, se consigue nitidez además de unos colores vivos y realistas. Además, con su tecnología HDR 10+ podrás ver todos los detalles sin importar lo brillante u oscura que sea una escena. Tus películas se verán en todo su esplendor.\r\nSi te gusta disfrutar de tus series y películas favoritas a través de internet, podrás hacerlo sin problemas con esta tele. Disfruta de apps como Netflix, HBO, Spotify, etc sin necesidad de nada más que tu televisor. Además, podrás controlarlo a través de tu móvil con la app SmartThings.",
			"specifications"=>"Tipo: LED UHD 4K - 55 pulgadas\r\nTamaño pantalla (cm): 138 cm\r\nTamaño pantalla (pulgadas): 55 \r\nDiseño Pantalla: Plano\r\nCalidad de imagen: UHD 4K\r\nSmart TV: Sí\r\nResolución: 3840 x 2160 píxeles\r\nConexiones: 3 HDMI \/ 2 USB \/ Óptica \/ LAN\r\nPuertos HDMI: 3\r\nPuertos USB: 2\r\nWi-Fi: Sí",
			"price"=>580,
			"categoryid"=>5,
			"subcategoryid"=>14,
			"providerid"=>4,
			"imgRoute"=>"Productos\/Television\/Televisores\/samsung01.png",
			"stock"=>20,
			"taxesid"=>2
		),
		array (
			"id"=>29,
			"object"=>"Proyector",
			"name"=>"",
			"brand"=>"Epson",
			"model"=>"EH-TW610",
			"description"=>"Este maravilloso proyector de Epson es capaz de ofrecerte una resolución nativa Full HD 1920 x 1080 con la que no te perderás ni un solo detalle de tus películas o series. La tecnología 3LCD con obturador de cristal líquido RGB te proporcionará unas texturas alucinantes. La luminosidad alcanza los 3000 lúmenes con lo cual podrás utilizar el proyector incluso en ambientes tenuemente iluminados. Y además, gracias a su lente óptico regulable podrás proyectar imágenes de entre 30 y ¡300 pulgadas!\r\nLa lámpara del proyector es la piedra angular sobre la que rota todo el funcionamiento del aparato. No tendrás que preocuparte por la durabilidad de la bombilla: tiene una vida útil de hasta 4.500 horas en la máxima resolución gracias a sus 210W de potencia.\r\nGracias a sus numerosos puertos podrás conectar el proyector a toda clase de dispositivos. No faltarán las entradas HDMI (2), VGA, MHL, USB, LAN inalámbrica (opcional) e incluso una salida de audio para que conectes unos altavoces externos, aunque el proyector dispone de sistema de audio propio de 10W.",
			"specifications"=>"Resolución: 1920 x 1080 píxeles\r\nContraste: 10.000:1\r\nBrillo: 3000 Lumen\r\n3D: no\r\nFormato de la pantalla: 16:9\r\nMedida de proyección: 30 - 300\r\nDistancia de proyección: 1.35 m - 1.64 m",
			"price"=>620,
			"categoryid"=>5,
			"subcategoryid"=>15,
			"providerid"=>6,
			"imgRoute"=>"Productos\/Television\/Proyectores\/epson01.png",
			"stock"=>20,
			"taxesid"=>2
		),
		array (
			"id"=>30,
			"object"=>"Cable",
			"name"=>"HDMI",
			"brand"=>"Giotek",
			"model"=>"XCS-HQ",
			"description"=>"Si quieres un cable HDMI de calidad superior para tus dispositivos HD, el Gioteck XCS-HQ es el tuyo. Con conectores chapados en oro de 24K, ofrece una resolución de hasta 4K.Imágenes nítidas e impactantesTanto si lo utilizas para tu TV de home cinema o en tus juegos 3D, este cable HDMI premium te ofrece una alta definición de imagen con gran riqueza de detalles, unos bordes perfectamente definidos y un contraste superior. Se puede utilizar para PS4, Xbox One, PS3, y PC. Además su diseño plano y de 3 metros asegurará una conexión libre de enredos.",
			"specifications"=>"Auriculares con altavoces de 40mm para sonido claro.\r\nMicrófono ajustable para chat de voz.\r\nDiseño ergonómico con almohadillas y diadema acolchadas.\r\nControles de audio independientes en el cable.",
			"price"=>15,
			"categoryid"=>6,
			"subcategoryid"=>16,
			"providerid"=>3,
			"imgRoute"=>"Productos\/Accesorios\/Cables\/hdmi01.png",
			"stock"=>20,
			"taxesid"=>2
		),
		array (
			"id"=>31,
			"object"=>'Cargador',
			"name"=>null,
			"brand"=>"Samsung",
			"model"=>"EP-TA20EWEUGWW",
			"description"=>"Ten siempre la batería llena de tu Smartphone o cualquier dispositivo, gracias al cargador EP-TA20EWEUGWW original de Samsung.\r\nSu tamaño ultra compacto, está diseñado para cargar en una toma múltiple sin que afecte al resto de aparatos que compartan la misma toma de corriente. Además, es muy fácil de transportar, cabe en cualquier bolsa o bolso.\r\nGracias a este cargador, tendrás todos tus dispositivos siempre cargados y listos para utilizarlos siempre que los necesites. Tendrás la batería del teléfono cargada en la mitad de tiempo, que te ofrece un cargador convencional. Además, incluye el cable USB que es reutilizable, con él puedes transferir datos entre tu teléfono y el ordenador. Es de color blanco.\r\nSerá tu compañero perfecto para cuando te vayas de viaje o estés fuera de casa.",
			"specifications"=>null,
			"price"=>16,
			"categoryid"=>6,
			"subcategoryid"=>17,
			"providerid"=>4,
			"imgRoute"=>"Productos\/Accesorios\/Cargadores\/samsung01.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>32,
			"object"=>'Auricular',
			"name"=>null,
			"brand"=>"Apple",
			"model"=>"AirPods",
			"description"=>"Un sonido claro y preciso cuando hablas y cuando te hablan, junto con la comodidad de no usar cables. Los auriculares inalámbricos Apple AirPods combinan sencillez con tecnología avanzada. Con conectividad Bluetooth, podrás escuchar música como nunca antes lo habías hecho.\r\nCon los auriculares inalámbricos Apple AirPods no te molestarán los cables ¡ya que no tienen y funcionan por Bluetooth! Además, son muy fáciles de activar y de usar, ya que funcionan cuando los llevas puestos y dejan de hacerlo cuando te los quitas.\r\nGracias al chip W1 tendrás una transmisión inalámbrica eficiente y un sonido de gran riqueza. Además, este chip gestiona la batería para un aprovechamiento óptimo.\r\nUsa los auriculares inalámbricos Apple AirPods durante 5 horas con tan solo una carga. Su estuche cargará los auriculares con solo guardarlos dentro de la caja y así poder utilizarlos hasta las 24 horas. Y si quieres conocer el nivel de batería solo tienes que acercarlos a tu iPhone.",
			"specifications"=>"Tipo: Auriculares de botón\r\nTipo de construcción: Intraurales\r\nTransmisión: Inalámbrica",
			"price"=>179,
			"categoryid"=>6,
			"subcategoryid"=>18,
			"providerid"=>5,
			"imgRoute"=>"Productos\/Accesorios\/Audio\/apple01.png",
			"stock"=>20,
			"taxesid"=>1
		),
		array (
			"id"=>33,
			"object"=>'Soporte',
			"name"=>null,
			"brand"=>"WM",
			"model"=>"2241",
			"description"=>"El soporte One For All WM 2241 te permitirá colocar tu televisor, de entre 13 y 40 pulgadas, para disfrutar con comodidad y precisión de todos los contenidos.\r\nEl soporte giratorio One For All puede girar 90° en posición horizontal, así como inclinarse 15° en vertical para que consiguas la ubicación perfecta. Mira tus películas, series y programas preferidos con una buena visualización desde cualquier lugar de la sala.\r\nEl soporte de 1 brazo WM 2241 te ofrece una instalación sencilla y rápida, gracias a los consejos de la App One For All.",
			"specifications"=>"Tipo: Soporte orientable 180°\r\nPulgadas mínimas: 13 \r\nPulgadas máximas: 40 \r\nMin. Screen diagonal (cm): 13 cm\r\nMax. Screen diagonal (cm): 40 cm\r\nCarga máxima: 30 kg",
			"price"=>20,
			"categoryid"=>6,
			"subcategoryid"=>19,
			"providerid"=>8,
			"imgRoute"=>"Productos\/Accesorios\/Video\/brazo01.png",
			"stock"=>20,
			"taxesid"=>3
		),
		array (
			"id"=>34,
			"object"=>'Bateria',
			"name"=>null,
			"brand"=>"GoPro",
			"model"=>"AABAT-001",
			"description"=>"Que nada frene tus aventuras. Lleva tu GoPro Hero 5 (no incluida) siempre contigo y asegúrate de no perder ni un instante de la acción con una batería extra a su altura: la GoPro AABAT-001.\r\nLa batería de iones de litio AABAT-001 dispone de una alta capacidad de 1220 mAh. Una batería recargable que te permitirá contar con una unidad de reserva para tu equipo, de forma que siempre estarás preparado para capturar la diversión a través de fotos y vídeos.",
			"specifications"=>"Tipo: Batería\r\nCompatible con: GoPro Hero 5 Black",
			"price"=>33,
			"categoryid"=>6,
			"subcategoryid"=>20,
			"providerid"=>9,
			"imgRoute"=>"Productos\/Accesorios\/Baterias\/gopro01.png",
			"stock"=>20,
			"taxesid"=>2
		)
	);
	/**
     * Run the database seeds.
     *
     * @return void
     */
	public function run()
	{
        Schema::disableForeignKeyConstraints();
		DB::table('products')->truncate();
		foreach ($this->arrayProductos as $producto) {
			$product = new Product();
			$product->object = $producto['object'];
			$product->model = $producto['model'];
			$product->name = $producto['name'];
			$product->brand = $producto['brand'];
			$product->description = $producto['description'];
			$product->specifications = $producto['specifications'];
			$product->price = $producto['price'];
			$product->categoryid = $producto['categoryid'];
			$product->subcategoryid = $producto['subcategoryid'];
			$product->providerid = $producto['providerid'];
			$product->imgRoute = $producto['imgRoute'];
			$product->stock = $producto['stock'];
			$product->taxesid = $producto['taxesid'];
			$product->save();
		}
        Schema::enableForeignKeyConstraints();
	}
}
